USE `seschool_02`;

CREATE TABLE `Clients` (
	`id` BIGINT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	`first_name` VARCHAR(50) NOT NULL,
	`last_name` VARCHAR(50) NOT NULL,
	`city` VARCHAR(50) NOT NULL,
	`age` TINYINT UNSIGNED NOT NULL,
	`balance` DECIMAL(10, 2) NOT NULL,
	`is_active` BOOLEAN NOT NULL DEFAULT FALSE
);